---
- name: Remove swapfile from /etc/fstab.
  ansible.posix.mount:
    name: swap
    fstype: swap
    state: absent
  # notify: Restart kubelet.service.
  become: true

- name: Disable swap.
  ansible.builtin.command:
    cmd: swapoff -a
  when: ansible_swaptotal_mb > 0
  # notify: Restart kubelet.service.
  become: true

- name: Disable swap from /etc/fstab.
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^/swap\.img(.*)$'
    line: '# /swap.img       none    swap    sw      0       0'
  become: true
